### PR TITLE
nodewatcher-agent: write json output feed to /tmp

### PR DESCRIPTION
**Pull request by avlasic**
For nodewatcher-agent default openwrt configuration writes json output to /www/nodewatcher/feed, but that means it writes output to flash every few minutes and it would make it wear out very soon.
It would be better to add symbolic link to write output to /tmp/nodewatcher_feed.

### CODE REVIEW

**Comment by kostko** [comment]
Can you add a comment in the Makefile just before the `ln` command, explaining this?

**Comment by mitar** [comment]
There is no need to close the pull request and make a new one. You can just add commits to the pull request (to the branch the pull request is made from) and the pull request will get updated.

**Comment by avlasic** [comment]
I know, but I accidentally deleted wrong branch and github doesn't warn that it will close pull request.

**Comment by mitar** [comment]
You can still restore the branch, no? It does not reopen the pull request?

**Comment by avlasic** [comment]
There is no option to restore it after closing branches page.
https://help.github.com/articles/viewing-branches-in-your-repository/ says that it can be restored here but no such option exsists. The interesting thing is that after modifying html in branches tab to restore different branch hash it does restore old one, and now there is an option on this page to restore it, looks like some sort of bug on github end.

**Pull request closed without merging**
